version: "3.8"

networks:
    turnobank_network:
        driver: bridge

services:
    nginx:
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        container_name: turnobank-nginx
        ports:
            - "8840:80"
            - "8850:443"
        restart: unless-stopped
        volumes:
            - ./public:/var/www/html/public
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./storage/app/public:/var/www/html/public/storage
        depends_on:
            - api
        networks:
            - turnobank_network

    api:
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        container_name: turnobank-api
        volumes:
            - ./:/var/www/html
        restart: unless-stopped
        tty: true
        environment:
            - APP_ENV=local
        networks:
            - turnobank_network
        depends_on:
            - mysql
            - cache

    mysql:
        platform: linux/x86_64 # Need to execute mysql in M1 Macbook
        image: mysql:8.0
        container_name: turnobank-mysql
        command: mysqld --performance_schema=off
        ports:
            - "3477:3306"
        volumes:
            - .data/mysql:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - turnobank_network

    cache:
        image: redis:6.2
        container_name: turnobank-cache
        command: redis-server --requirepass ${REDIS_PASSWORD}
        restart: unless-stopped
        networks:
            - turnobank_network
